=== geekswagg/blueprints/content/json-schemas/src/layouts/footer.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "layouts/footer.schema.json",
  "title": "JSON Schema for Footer Page",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Reference to the json schema which the document will be validated by."
    },
    "_layout": {
      "type": "string",
      "enum": [ "footer" ],
      "description": "Type of layout."
    },
    "_isSingleton": {
      "type": "boolean"
    },
    "primaryLinks": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "to": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "isExternal": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      }
    },
    "secondaryLinks": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "to": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "isExternal": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "required": [ "_layout", "_isSingleton" ],
  "additionalProperties": false
}

=== geekswagg/blueprints/docs/static/780786d8987d200aa2ff473d2013cef8/footer.json
{
  "_layout": "footer",
  "_isSingleton": true,
  "primaryLinks": [
    {
      "to": "/getting-started/",
      "text": "Getting Started",
      "isExternal": false
    },
    {
      "to": "/guidance/introduction",
      "text": "Guidance",
      "isExternal": false
    },
    {
      "to": "/starters/introduction",
      "text": "Starters",
      "isExternal": false
    },
    {
      "to": "/cms/introduction",
      "text": "CMS",
      "isExternal": false
    }
  ],
  "secondaryLinks": [
    {
      "to": "https://github.com/microsoft/blueprints",
      "text": "GitHub",
      "isExternal": true
    },
    {
      "to": "https://develop.fluentui.dev/",
      "text": "Fluent",
      "isExternal": true
    },
    {
      "to": "https://microsoft.com/",
      "text": "Microsoft Design",
      "isExternal": true
    }
  ]
}
